apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndvi-processing
  namespace: satellite-ndvi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ndvi-processing
  template:
    metadata:
      labels:
        app: ndvi-processing
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: processor
        image: chinnikrishnak02/satellite-ndvi-processor:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: ndvi-config
          - secretRef:
              name: ndvi-secrets
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ndvi-data-pvc
